export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, {
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Methods": "POST, OPTIONS",
          "Access-Control-Allow-Headers": "Content-Type",
        },
      });
    }

    if (url.pathname === "/favicon.ico" || url.pathname === "/favicon.png") {
      const favicon = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABmklEQVR4nO2bQY7DIAxFnaiaRQ/QM/RKXczpZjFX6hl6gC5m01lZQhYB7AAG7LdKopD4fz6kSsMGnbje7h/O+e/Xc2tVS0izm3AF52hlSPWL1hZOqW1EtYu1Fk6pZcTpi/QWTjlrhLixtnCK1Ihd0mg08QDymtgGjCgekdRWHJuRhccoHRJFCZhNPEB5zVkDZhSPlNQumgRXImnAzL2P5DQcGrCCeCSlJTpTSsR//Ty4Tdj8ff+eah97MvgcQA+sFH1KTJsnINxZufcRqtETgBsWeh8JtXoCAGz1PoKaLz1vevaHTAt8CGgXoM1ucfwj19v94wnQLkAb8wZ0fQxy3xn0eGyaT4AboF2ANm6AdgHauAHaBWiz9/oaa0Ter+fm7wO0C9DGDQDo91XmSKBmTwBuWEpBqNUTEO5YSAHV6AmgB1ZOgX8hEiFqwIopONKUFLrKnyapDk0OgRWSkNPgc0DuhJlTUFJ7UQJmNKG0Zraw0SdGbmex54CR0yCpTTQJjmiCtCZfNlerELMLJylml85SzC6ePmLU5fP/2JmedN7q5LgAAAAASUVORK5CYII=";
      const bytes = Uint8Array.from(atob(favicon), c => c.charCodeAt(0));
      return new Response(bytes, {
        headers: { "Content-Type": "image/png", "Cache-Control": "public, max-age=86400" },
      });
    }

    if (url.pathname === "/api/audit" && request.method === "POST") {
      const body = await request.json();
      const orgName = (body.orgName || "").trim().toLowerCase();
      const existing = await env.FUNDRI_KV.get("org:" + orgName);
      if (existing) {
        return new Response(JSON.stringify({ error: "already_submitted" }), {
          headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
        });
      }
      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: "claude-sonnet-4-20250514",
          max_tokens: 1000,
          messages: [{ role: "user", content: body.prompt }],
        }),
      });
      const data = await response.json();
      await env.FUNDRI_KV.put("org:" + orgName, "1");
      return new Response(JSON.stringify(data), {
        headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      });
    }

    if (url.pathname === "/api/story" && request.method === "POST") {
      const body = await request.json();
      const orgName = (body.org || "").trim().toLowerCase();

      if (orgName) {
        const storyCount = await env.FUNDRI_KV.get("story:" + orgName);
        const count = storyCount ? parseInt(storyCount) : 0;
        if (count >= 2) {
          return new Response(JSON.stringify({ error: "story_limit_reached" }), {
            headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
          });
        }
      }

      const content = [];

      if (body.images && body.images.length > 0) {
        body.images.forEach(function(img, i) {
          content.push({
            type: "image",
            source: {
              type: "base64",
              media_type: img.mediaType || "image/jpeg",
              data: img.data,
            },
          });
        });
      }

      content.push({
        type: "text",
        text: `You are an expert impact storyteller for NGOs and civil society organizations in East Africa. Based on the provided photos and context, generate three outputs.

CONTEXT:
- Organization: ${body.org || "Not specified"}
- What happened: ${body.what || "Not specified"}
- Audience: ${body.audience || "Donor report"}
- Number of photos provided: ${body.images ? body.images.length : 0}

Generate exactly this JSON (no markdown, no backticks, raw JSON only):
{
  "story": "<A compelling 300-400 word impact narrative written in third person. Weave details from all provided photos together into one cohesive story. Start with the human element. Be specific about what you see. End with broader impact and forward-looking statement.>",
  "social": "<2-3 sentence social media post. Punchy, human, specific. Include one relevant hashtag at the end.>",
  "quote": "<A powerful pull quote of 1-2 sentences, written as if from a community member or beneficiary. Put it in quotation marks.>"
}

Be specific, human, and authentic. Avoid generic development sector jargon. Make it feel real.`,
      });

      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: "claude-sonnet-4-20250514",
          max_tokens: 1500,
          messages: [{ role: "user", content }],
        }),
      });

      const data = await response.json();

      if (orgName) {
        const storyCount = await env.FUNDRI_KV.get("story:" + orgName);
        const count = storyCount ? parseInt(storyCount) : 0;
        await env.FUNDRI_KV.put("story:" + orgName, String(count + 1));
      }

      return new Response(JSON.stringify(data), {
        headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      });
    }

    if (url.pathname === "/api/feedback" && request.method === "POST") {
      const body = await request.json();
      const key = "feedback:" + Date.now() + ":" + Math.random().toString(36).slice(2);
      await env.FUNDRI_KV.put(key, JSON.stringify({
        rating: body.rating || "",
        comment: body.comment || "",
        email: body.email || "",
        org: body.org || "",
        timestamp: new Date().toISOString(),
      }));
      return new Response(JSON.stringify({ ok: true }), {
        headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      });
    }

    if (url.pathname === "/story") {
      return new Response(getStoryHTML(), {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    if (url.pathname === "/" || url.pathname === "/index.html") {
      return new Response(getHTML(), {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    }

    return new Response("Not found", { status: 404 });
  },
};

function getStoryHTML() {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">',
    '<title>Fundri - Impact Story Builder</title>',
    '<link rel="icon" type="image/png" href="/favicon.png">',
    '<link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">',
    '<style>',
    '* { box-sizing: border-box; margin: 0; padding: 0; }',
    'html, body { width: 100%; overflow-x: hidden; }',
    'body { font-family: DM Sans, sans-serif; background: #0a1628; min-height: 100vh; color: #e8edf5; }',
    '.hero { background: linear-gradient(135deg, #0a1628 0%, #0f2347 50%, #0a1628 100%); padding: 2.5rem 1.5rem 2rem; text-align: center; position: relative; overflow: hidden; }',
    '.logo { font-family: Syne, sans-serif; font-size: 2rem; font-weight: 700; color: #10b981; letter-spacing: -0.5px; margin-bottom: 0.25rem; line-height: 1.4; }',
    '.logo span { color: #e8edf5; }',
    '.logo a { text-decoration: none; }',
    '.tagline { font-size: 0.85rem; color: #6b7fa3; letter-spacing: 0.15em; text-transform: uppercase; margin-bottom: 1.5rem; }',
    '.hero h1 { font-family: Syne, sans-serif; font-size: clamp(1.4rem, 5vw, 1.9rem); font-weight: 600; color: #e8edf5; line-height: 1.4; max-width: 520px; margin: 0 auto 0.75rem; }',
    '.hero h1 em { color: #10b981; font-style: normal; }',
    '.hero p { font-size: clamp(0.85rem, 3vw, 0.9rem); color: #8a9bbf; max-width: 420px; margin: 0 auto; line-height: 1.6; }',
    '.badge { display: inline-flex; align-items: center; gap: 6px; background: rgba(16,185,129,0.1); border: 1px solid rgba(16,185,129,0.25); color: #10b981; font-size: 0.75rem; font-weight: 500; padding: 4px 12px; border-radius: 20px; margin-bottom: 1.25rem; letter-spacing: 0.05em; }',
    '.badge::before { content: ""; width: 6px; height: 6px; background: #10b981; border-radius: 50%; animation: pulse 2s infinite; }',
    '@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }',
    '.tool-nav { display: flex; gap: 0.75rem; justify-content: center; margin-bottom: 1.5rem; flex-wrap: wrap; }',
    '.tool-pill { display: inline-flex; align-items: center; gap: 6px; padding: 6px 14px; border-radius: 20px; font-size: 0.8rem; text-decoration: none; border: 1px solid rgba(255,255,255,0.1); color: #6b7fa3; transition: all 0.2s; }',
    '.tool-pill:hover { border-color: rgba(16,185,129,0.4); color: #10b981; }',
    '.tool-pill.active { border-color: #10b981; color: #10b981; background: rgba(16,185,129,0.08); }',
    '.form-container { max-width: 620px; margin: 0 auto; padding: 1.5rem; width: 100%; }',
    '.form-card { background: #0f1e3a; border: 1px solid rgba(255,255,255,0.07); border-radius: 16px; padding: 1.5rem; margin-bottom: 1rem; }',
    '.form-card h2 { font-family: Syne, sans-serif; font-size: 1rem; font-weight: 600; color: #c8d4e8; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 8px; line-height: 1.4; }',
    '.step-num { width: 24px; height: 24px; background: rgba(16,185,129,0.15); border: 1px solid rgba(16,185,129,0.3); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.7rem; color: #10b981; font-weight: 600; flex-shrink: 0; }',
    '.field-group { margin-bottom: 1.25rem; }',
    '.field-group:last-child { margin-bottom: 0; }',
    'label { display: block; font-size: 0.8rem; font-weight: 500; color: #8a9bbf; margin-bottom: 6px; letter-spacing: 0.03em; text-transform: uppercase; }',
    'input[type=text], select, textarea { width: 100%; background: #0a1628; border: 1px solid rgba(255,255,255,0.1); border-radius: 8px; padding: 10px 14px; font-size: 0.9rem; color: #e8edf5; font-family: DM Sans, sans-serif; transition: border-color 0.2s; outline: none; -webkit-appearance: none; }',
    'input[type=text]:focus, select:focus, textarea:focus { border-color: rgba(16,185,129,0.5); }',
    'select option { background: #0f1e3a; color: #e8edf5; }',
    'textarea { resize: vertical; min-height: 70px; line-height: 1.5; }',
    '.upload-area { border: 2px dashed rgba(16,185,129,0.3); border-radius: 12px; padding: 1.5rem; text-align: center; cursor: pointer; transition: all 0.2s; background: rgba(16,185,129,0.03); position: relative; }',
    '.upload-area:hover { border-color: rgba(16,185,129,0.6); background: rgba(16,185,129,0.06); }',
    '.upload-area.has-file { border-color: #10b981; background: rgba(16,185,129,0.08); }',
    '.upload-icon { font-size: 2.5rem; margin-bottom: 0.75rem; display: block; }',
    '.upload-text { color: #8a9bbf; font-size: 0.9rem; margin-bottom: 0.25rem; }',
    '.upload-hint { color: #4a6a8a; font-size: 0.75rem; margin-bottom: 0.5rem; }',
    '.upload-limit { color: #10b981; font-size: 0.75rem; font-weight: 600; }',
    '#fileInput { position: absolute; inset: 0; opacity: 0; cursor: pointer; width: 100%; height: 100%; }',
    '.preview-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.5rem; margin-top: 0.75rem; }',
    '.preview-item { position: relative; border-radius: 8px; overflow: hidden; aspect-ratio: 1; }',
    '.preview-item img { width: 100%; height: 100%; object-fit: cover; }',
    '.preview-item .remove-btn { position: absolute; top: 4px; right: 4px; width: 20px; height: 20px; background: rgba(226,75,74,0.9); border: none; border-radius: 50%; color: white; font-size: 12px; cursor: pointer; display: flex; align-items: center; justify-content: center; line-height: 1; }',
    '.photo-count { color: #10b981; font-size: 0.8rem; margin-top: 0.5rem; font-weight: 600; }',
    '.submit-btn { width: 100%; background: #10b981; color: #0a1628; border: none; border-radius: 10px; padding: 14px 24px; font-family: Syne, sans-serif; font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.2s; margin-top: 0.5rem; -webkit-appearance: none; }',
    '.submit-btn:disabled { background: #1e3a2e; color: #3a6b55; cursor: not-allowed; }',
    '.error-msg { background: rgba(226,75,74,0.1); border: 1px solid rgba(226,75,74,0.2); border-radius: 8px; padding: 12px 16px; color: #f09595; font-size: 0.85rem; margin-top: 0.75rem; display: none; }',
    '.result-section { display: none; max-width: 620px; margin: 0 auto; padding: 0 1.5rem 3rem; }',
    '.result-card { background: #0f1e3a; border: 1px solid rgba(255,255,255,0.07); border-radius: 12px; padding: 1.5rem; margin-bottom: 0.75rem; }',
    '.result-card h3 { font-family: Syne, sans-serif; font-size: 0.8rem; font-weight: 600; color: #10b981; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 1rem; display: flex; align-items: center; gap: 8px; line-height: 1.4; }',
    '.result-card h3::before { content: ""; width: 3px; height: 14px; background: #10b981; border-radius: 2px; flex-shrink: 0; }',
    '.result-content { font-size: 0.9rem; color: #a8b8d4; line-height: 1.8; white-space: pre-wrap; }',
    '.quote-content { font-size: 1rem; color: #c8d4e8; line-height: 1.7; font-style: italic; border-left: 3px solid #10b981; padding-left: 1rem; }',
    '.copy-btn { display: inline-flex; align-items: center; gap: 6px; background: transparent; border: 1px solid rgba(255,255,255,0.1); color: #6b7fa3; font-size: 0.75rem; padding: 5px 12px; border-radius: 6px; cursor: pointer; margin-top: 0.75rem; font-family: DM Sans, sans-serif; transition: all 0.2s; }',
    '.copy-btn:hover { border-color: rgba(16,185,129,0.4); color: #10b981; }',
    '.copy-btn.copied { border-color: #10b981; color: #10b981; }',
    '.loading-state { text-align: center; padding: 3rem 2rem; }',
    '.spinner { width: 40px; height: 40px; border: 2px solid rgba(16,185,129,0.2); border-top-color: #10b981; border-radius: 50%; animation: spin 0.8s linear infinite; margin: 0 auto 1rem; }',
    '@keyframes spin { to { transform: rotate(360deg); } }',
    '.loading-title { font-family: Syne, sans-serif; font-size: 1rem; color: #c8d4e8; margin-bottom: 0.5rem; }',
    '.loading-state p { color: #6b7fa3; font-size: 0.85rem; }',
    '.reset-btn { width: 100%; background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 10px; padding: 12px; color: #6b7fa3; font-family: DM Sans, sans-serif; font-size: 0.85rem; cursor: pointer; margin-top: 0.5rem; }',
    '.footer-contact { text-align: center; font-size: 0.8rem; color: #4a5a7a; padding: 0 1rem 2rem; margin-top: 0.25rem; }',
    '.footer-contact a { color: #10b981; text-decoration: none; }',
    '.disclaimer { text-align: center; font-size: 0.75rem; color: #4a5a7a; padding: 0 1rem 0.5rem; }',
    '@media (max-width: 600px) { .hero { padding: 2rem 1rem 1.5rem; } .form-container { padding: 1rem; } .result-section { padding: 0 1rem 2rem; } .form-card { padding: 1.25rem; } }',
    '</style>',
    '</head>',
    '<body>',
    '<div class="hero">',
    '<div class="logo"><a href="/">Fund<span>ri</span></a></div>',
    '<div class="tagline">AI-Powered NGO Tools</div>',
    '<div class="tool-nav">',
    '<a href="/" class="tool-pill">Fundability Audit</a>',
    '<a href="/story" class="tool-pill active">Impact Story Builder</a>',
    '</div>',
    '<div class="badge">Free Tool</div>',
    '<h1>Turn field moments into <em>compelling stories</em></h1>',
    '<p>Upload up to 3 photos from the field. Get a donor-ready impact story, social media post, and pull quote instantly.</p>',
    '</div>',
    '<div class="form-container" id="formSection">',
    '<div class="form-card">',
    '<h2><span class="step-num">1</span> Upload from the field</h2>',
    '<div class="field-group">',
    '<div class="upload-area" id="uploadArea" onclick="document.getElementById(\'fileInput\').click()">',
    '<input type="file" id="fileInput" accept="image/*" multiple capture="environment">',
    '<span class="upload-icon">&#128247;</span>',
    '<p class="upload-text">Tap to take photos or upload from your gallery</p>',
    '<p class="upload-hint">Better context = better story</p>',
    '<p class="upload-limit">Maximum 3 photos</p>',
    '</div>',
    '<div class="preview-grid" id="previewGrid"></div>',
    '<p class="photo-count" id="photoCount"></p>',
    '</div>',
    '</div>',
    '<div class="form-card">',
    '<h2><span class="step-num">2</span> Add context</h2>',
    '<div class="field-group">',
    '<label>What happened here?</label>',
    '<textarea id="whatHappened" placeholder="e.g. We trained 40 women on clean water practices in Kisumu. 200 households now have access to safe water." style="min-height: 80px;"></textarea>',
    '</div>',
    '<div class="field-group">',
    '<label>Organization name</label>',
    '<input type="text" id="orgName" placeholder="e.g. Maji Safi Community Trust" />',
    '</div>',
    '<div class="field-group">',
    '<label>This story is for</label>',
    '<select id="audience">',
    '<option value="Donor report">Donor report</option>',
    '<option value="Social media">Social media</option>',
    '<option value="Annual report">Annual report</option>',
    '<option value="Internal update">Internal update</option>',
    '<option value="Grant application">Grant application</option>',
    '</select>',
    '</div>',
    '</div>',
    '<button class="submit-btn" onclick="generateStory()">Generate my impact story &#8594;</button>',
    '<div class="error-msg" id="errorMsg"></div>',
    '<p class="disclaimer" style="margin-top: 1rem;">Your org name is stored only to manage usage limits (max 2 stories per org). Feedback you submit is stored to help us improve Fundri. Your data is never shared with third parties.</p>',
    '<p class="footer-contact">Get in touch &mdash; <a href="mailto:hello@getfundri.com">hello@getfundri.com</a></p>',
    '</div>',
    '<div class="result-section" id="resultSection">',
    '<div id="loadingState" class="loading-state result-card">',
    '<div class="spinner"></div>',
    '<p class="loading-title" id="loadingTitle">Uploading and analyzing your photos...</p>',
    '<p>This may take 10-15 seconds for multiple photos</p>',
    '</div>',
    '<div id="storyResults" style="display:none;">',
    '<div class="result-card">',
    '<h3>Impact narrative</h3>',
    '<div class="result-content" id="storyText"></div>',
    '<button class="copy-btn" onclick="copyText(\'storyText\', this)">Copy narrative</button>',
    '</div>',
    '<div class="result-card">',
    '<h3>Pull quote</h3>',
    '<div class="quote-content" id="quoteText"></div>',
    '<button class="copy-btn" onclick="copyText(\'quoteText\', this)">Copy quote</button>',
    '</div>',
    '<div class="result-card">',
    '<h3>Social media post</h3>',
    '<div class="result-content" id="socialText"></div>',
    '<button class="copy-btn" onclick="copyText(\'socialText\', this)">Copy post</button>',
    '</div>',
    '<button class="reset-btn" id="resetBtn" onclick="resetForm()">&#8592; Generate another story</button>',
    '<p class="footer-contact" style="margin-top: 1.5rem;">Get in touch &mdash; <a href="mailto:hello@getfundri.com">hello@getfundri.com</a></p>',
    '</div>',
    '</div>',
    '<script>',
    'var uploadedImages = [];',
    'var storyCount = 0;',
    '',
    'document.getElementById("fileInput").addEventListener("change", function(e) {',
    '  var files = Array.from(e.target.files);',
    '  var remaining = 3 - uploadedImages.length;',
    '  if (remaining <= 0) {',
    '    alert("Maximum 3 photos allowed. Remove a photo to add another.");',
    '    return;',
    '  }',
    '  files = files.slice(0, remaining);',
    '  files.forEach(function(file) {',
    '    if (!file.type.startsWith("image/")) return;',
    '    var reader = new FileReader();',
    '    reader.onload = function(ev) {',
    '      var img = new Image();',
    '      img.onload = function() {',
    '        var canvas = document.createElement("canvas");',
    '        var maxW = 1024; var maxH = 1024;',
    '        var w = img.width; var h = img.height;',
    '        if (w > maxW) { h = h * maxW / w; w = maxW; }',
    '        if (h > maxH) { w = w * maxH / h; h = maxH; }',
    '        canvas.width = w; canvas.height = h;',
    '        canvas.getContext("2d").drawImage(img, 0, 0, w, h);',
    '        var compressed = canvas.toDataURL("image/jpeg", 0.8);',
    '        var id = Date.now() + Math.random();',
    '        uploadedImages.push({ id: id, data: compressed.split(",")[1], mediaType: "image/jpeg" });',
    '        renderPreviews();',
    '      };',
    '      img.src = ev.target.result;',
    '    };',
    '    reader.readAsDataURL(file);',
    '  });',
    '  document.getElementById("fileInput").value = "";',
    '});',
    '',
    'function renderPreviews() {',
    '  var grid = document.getElementById("previewGrid");',
    '  var count = document.getElementById("photoCount");',
    '  var area = document.getElementById("uploadArea");',
    '  grid.innerHTML = "";',
    '  uploadedImages.forEach(function(img) {',
    '    var div = document.createElement("div");',
    '    div.className = "preview-item";',
    '    div.innerHTML = \'<img src="data:image/jpeg;base64,\' + img.data + \'" alt="preview"><button class="remove-btn" onclick="removeImage(\\\'\' + img.id + \'\\\')">&#215;</button>\';',
    '    grid.appendChild(div);',
    '  });',
    '  if (uploadedImages.length > 0) {',
    '    count.textContent = uploadedImages.length + " of 3 photos added" + (uploadedImages.length < 3 ? " — tap above to add more" : " — maximum reached");',
    '    area.classList.add("has-file");',
    '  } else {',
    '    count.textContent = "";',
    '    area.classList.remove("has-file");',
    '  }',
    '}',
    '',
    'function removeImage(id) {',
    '  uploadedImages = uploadedImages.filter(function(img) { return img.id !== id; });',
    '  renderPreviews();',
    '}',
    '',
    'async function generateStory() {',
    '  var what = document.getElementById("whatHappened").value.trim();',
    '  var org = document.getElementById("orgName").value.trim();',
    '  var audience = document.getElementById("audience").value;',
    '  var errorMsg = document.getElementById("errorMsg");',
    '  errorMsg.style.display = "none";',
    '  if (!what && uploadedImages.length === 0) {',
    '    errorMsg.textContent = "Please upload at least one photo or describe what happened — or both.";',
    '    errorMsg.style.display = "block"; return;',
    '  }',
    '  var btn = document.querySelector(".submit-btn");',
    '  btn.disabled = true;',
    '  btn.textContent = uploadedImages.length > 1 ? "Analyzing " + uploadedImages.length + " photos..." : "Generating...";',
    '  document.getElementById("formSection").style.display = "none";',
    '  document.getElementById("resultSection").style.display = "block";',
    '  document.getElementById("loadingState").style.display = "block";',
    '  document.getElementById("storyResults").style.display = "none";',
    '  if (uploadedImages.length > 1) {',
    '    document.getElementById("loadingTitle").textContent = "Analyzing " + uploadedImages.length + " photos and crafting your story...";',
    '  }',
    '  try {',
    '    var payload = {',
    '      org: org,',
    '      what: what,',
    '      audience: audience,',
    '      images: uploadedImages.map(function(img) { return { data: img.data, mediaType: img.mediaType }; })',
    '    };',
    '    var response = await fetch("/api/story", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    '      body: JSON.stringify(payload)',
    '    });',
    '    var data = await response.json();',
    '    if (data.error === "story_limit_reached") {',
    '      document.getElementById("formSection").style.display = "block";',
    '      document.getElementById("resultSection").style.display = "none";',
    '      errorMsg.textContent = "Your organization has reached the free limit of 2 stories. Email hello@getfundri.com to generate more.";',
    '      errorMsg.style.display = "block";',
    '      btn.disabled = false; btn.textContent = "Generate my impact story";',
    '      return;',
    '    }',
    '    var text = data.content[0].text.trim();',
    '    var result;',
    '    try { result = JSON.parse(text); }',
    '    catch(e) { var m = text.match(/\\{[\\s\\S]*\\}/); result = JSON.parse(m[0]); }',
    '    document.getElementById("storyText").textContent = result.story || "";',
    '    document.getElementById("quoteText").textContent = result.quote || "";',
    '    document.getElementById("socialText").textContent = result.social || "";',
    '    document.getElementById("loadingState").style.display = "none";',
    '    document.getElementById("storyResults").style.display = "block";',
    '    storyCount++;',
    '    if (storyCount >= 2) {',
    '      var rb = document.getElementById("resetBtn");',
    '      rb.textContent = "Need more stories? Email hello@getfundri.com";',
    '      rb.style.cursor = "default";',
    '      rb.onclick = null;',
    '    }',
    '  } catch(err) {',
    '    document.getElementById("formSection").style.display = "block";',
    '    document.getElementById("resultSection").style.display = "none";',
    '    errorMsg.textContent = "Something went wrong. Please try again.";',
    '    errorMsg.style.display = "block";',
    '    btn.disabled = false; btn.textContent = "Generate my impact story";',
    '  }',
    '}',
    '',
    'function copyText(id, btn) {',
    '  var text = document.getElementById(id).textContent;',
    '  navigator.clipboard.writeText(text).then(function() {',
    '    var orig = btn.textContent;',
    '    btn.textContent = "Copied!"; btn.classList.add("copied");',
    '    setTimeout(function() { btn.textContent = orig; btn.classList.remove("copied"); }, 2000);',
    '  });',
    '}',
    '',
    'function resetForm() {',
    '  document.getElementById("resultSection").style.display = "none";',
    '  document.getElementById("formSection").style.display = "block";',
    '  document.querySelector(".submit-btn").disabled = false;',
    '  document.querySelector(".submit-btn").textContent = "Generate my impact story";',
    '  uploadedImages = [];',
    '  renderPreviews();',
    '  document.getElementById("loadingTitle").textContent = "Uploading and analyzing your photos...";',
    '}',
    '<\/script>',
    '</body>',
    '</html>'
  ].join('\n');
  return html;
}

function getHTML() {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">',
    '<title>Fundri - AI-Powered NGO Fundability Intelligence</title>',
    '<link rel="icon" type="image/png" href="/favicon.png">',
    '<link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">',
    '<style>',
    '* { box-sizing: border-box; margin: 0; padding: 0; }',
    'html, body { width: 100%; overflow-x: hidden; }',
    'body { font-family: DM Sans, sans-serif; background: #0a1628; min-height: 100vh; color: #e8edf5; }',
    '.hero { background: linear-gradient(135deg, #0a1628 0%, #0f2347 50%, #0a1628 100%); padding: 2.5rem 1.5rem 2rem; text-align: center; position: relative; overflow: hidden; width: 100%; }',
    '.logo { font-family: Syne, sans-serif; font-size: 2rem; font-weight: 700; color: #10b981; letter-spacing: -0.5px; margin-bottom: 0.5rem; line-height: 1.4; overflow: visible; }',
    '.logo span { color: #e8edf5; }',
    '.tagline { font-size: 0.85rem; color: #6b7fa3; letter-spacing: 0.15em; text-transform: uppercase; margin-bottom: 1rem; }',
    '.tool-nav { display: flex; gap: 0.75rem; justify-content: center; margin-bottom: 1.5rem; flex-wrap: wrap; }',
    '.tool-pill { display: inline-flex; align-items: center; gap: 6px; padding: 6px 14px; border-radius: 20px; font-size: 0.8rem; text-decoration: none; border: 1px solid rgba(255,255,255,0.1); color: #6b7fa3; transition: all 0.2s; }',
    '.tool-pill:hover { border-color: rgba(16,185,129,0.4); color: #10b981; }',
    '.tool-pill.active { border-color: #10b981; color: #10b981; background: rgba(16,185,129,0.08); }',
    '.hero h1 { font-family: Syne, sans-serif; font-size: clamp(1.4rem, 5vw, 1.9rem); font-weight: 600; color: #e8edf5; line-height: 1.4; max-width: 520px; margin: 0 auto 0.75rem; padding-bottom: 0.15em; overflow: visible; }',
    '.hero h1 em { color: #10b981; font-style: normal; display: inline-block; line-height: 1.4; padding-bottom: 0.1em; overflow: visible; }',
    '.hero p { font-size: clamp(0.85rem, 3vw, 0.95rem); color: #8a9bbf; max-width: 420px; margin: 0 auto; line-height: 1.6; }',
    '.badge { display: inline-flex; align-items: center; gap: 6px; background: rgba(16,185,129,0.1); border: 1px solid rgba(16,185,129,0.25); color: #10b981; font-size: 0.75rem; font-weight: 500; padding: 4px 12px; border-radius: 20px; margin-bottom: 1.25rem; letter-spacing: 0.05em; }',
    '.badge::before { content: ""; width: 6px; height: 6px; background: #10b981; border-radius: 50%; animation: pulse 2s infinite; }',
    '@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }',
    '.form-container { max-width: 620px; margin: 0 auto; padding: 1.5rem; width: 100%; }',
    '.form-card { background: #0f1e3a; border: 1px solid rgba(255,255,255,0.07); border-radius: 16px; padding: 1.5rem; margin-bottom: 1rem; width: 100%; }',
    '.form-card h2 { font-family: Syne, sans-serif; font-size: 1rem; font-weight: 600; color: #c8d4e8; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 8px; line-height: 1.4; }',
    '.step-num { width: 24px; height: 24px; background: rgba(16,185,129,0.15); border: 1px solid rgba(16,185,129,0.3); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.7rem; color: #10b981; font-weight: 600; flex-shrink: 0; }',
    '.field-group { margin-bottom: 1.25rem; }',
    '.field-group:last-child { margin-bottom: 0; }',
    'label { display: block; font-size: 0.8rem; font-weight: 500; color: #8a9bbf; margin-bottom: 6px; letter-spacing: 0.03em; text-transform: uppercase; }',
    'input[type=text], input[type=email], select, textarea { width: 100%; background: #0a1628; border: 1px solid rgba(255,255,255,0.1); border-radius: 8px; padding: 10px 14px; font-size: 0.9rem; color: #e8edf5; font-family: DM Sans, sans-serif; transition: border-color 0.2s; outline: none; -webkit-appearance: none; }',
    'input[type=text]:focus, input[type=email]:focus, select:focus, textarea:focus { border-color: rgba(16,185,129,0.5); }',
    'select option { background: #0f1e3a; color: #e8edf5; }',
    'textarea { resize: vertical; min-height: 80px; line-height: 1.5; }',
    '.field-row { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }',
    '.submit-btn { width: 100%; background: #10b981; color: #0a1628; border: none; border-radius: 10px; padding: 14px 24px; font-family: Syne, sans-serif; font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.2s; margin-top: 0.5rem; -webkit-appearance: none; }',
    '.submit-btn:disabled { background: #1e3a2e; color: #3a6b55; cursor: not-allowed; }',
    '.disclaimer { text-align: center; font-size: 0.75rem; color: #4a5a7a; padding: 0 1rem 0.5rem; }',
    '.footer-contact { text-align: center; font-size: 0.8rem; color: #4a5a7a; padding: 0 1rem 2rem; margin-top: 0.25rem; }',
    '.footer-contact a { color: #10b981; text-decoration: none; }',
    '.result-section { display: none; max-width: 620px; margin: 0 auto; padding: 0 1.5rem 3rem; width: 100%; }',
    '.result-header { background: linear-gradient(135deg, #0f2a1a, #0f1e3a); border: 1px solid rgba(16,185,129,0.2); border-radius: 16px; padding: 1.5rem; margin-bottom: 1rem; text-align: center; }',
    '.score-ring { width: 90px; height: 90px; border-radius: 50%; background: conic-gradient(#10b981 0%, #10b981 var(--score-pct), #1a2f4a var(--score-pct), #1a2f4a 100%); display: flex; align-items: center; justify-content: center; margin: 0 auto 1rem; position: relative; }',
    '.score-ring::before { content: ""; width: 70px; height: 70px; background: #0a1628; border-radius: 50%; position: absolute; }',
    '.score-number { font-family: Syne, sans-serif; font-size: 1.4rem; font-weight: 700; color: #10b981; position: relative; z-index: 1; line-height: 1.4; }',
    '.score-label { font-family: Syne, sans-serif; font-size: 1.1rem; font-weight: 600; color: #c8d4e8; margin-bottom: 0.25rem; line-height: 1.4; }',
    '.score-sub { font-size: 0.8rem; color: #6b7fa3; }',
    '.result-card { background: #0f1e3a; border: 1px solid rgba(255,255,255,0.07); border-radius: 12px; padding: 1.5rem; margin-bottom: 0.75rem; }',
    '.result-card h3 { font-family: Syne, sans-serif; font-size: 0.8rem; font-weight: 600; color: #10b981; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 1rem; display: flex; align-items: center; gap: 8px; line-height: 1.4; }',
    '.result-card h3::before { content: ""; width: 3px; height: 14px; background: #10b981; border-radius: 2px; flex-shrink: 0; }',
    '.result-content { font-size: 0.9rem; color: #a8b8d4; line-height: 1.7; white-space: pre-wrap; }',
    '.loading-state { text-align: center; padding: 3rem 2rem; }',
    '.spinner { width: 40px; height: 40px; border: 2px solid rgba(16,185,129,0.2); border-top-color: #10b981; border-radius: 50%; animation: spin 0.8s linear infinite; margin: 0 auto 1rem; }',
    '@keyframes spin { to { transform: rotate(360deg); } }',
    '.loading-state p { color: #6b7fa3; font-size: 0.85rem; }',
    '.loading-title { font-family: Syne, sans-serif; font-size: 1rem; color: #c8d4e8; margin-bottom: 0.5rem; line-height: 1.4; }',
    '.reset-btn { width: 100%; background: transparent; border: 1px solid rgba(255,255,255,0.1); border-radius: 10px; padding: 12px; color: #6b7fa3; font-family: DM Sans, sans-serif; font-size: 0.85rem; cursor: pointer; margin-top: 0.5rem; }',
    '.error-msg { background: rgba(226,75,74,0.1); border: 1px solid rgba(226,75,74,0.2); border-radius: 8px; padding: 12px 16px; color: #f09595; font-size: 0.85rem; margin-top: 0.75rem; display: none; }',
    '.feedback-card { background: #0f1e3a; border: 1px solid rgba(16,185,129,0.2); border-radius: 12px; padding: 1.5rem; margin-bottom: 0.75rem; }',
    '.feedback-card h3 { font-family: Syne, sans-serif; font-size: 0.85rem; font-weight: 600; color: #10b981; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 1rem; }',
    '.rating-buttons { display: flex; gap: 0.75rem; margin-bottom: 1rem; }',
    '.rating-btn { flex: 1; padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.1); background: #0a1628; color: #8a9bbf; font-family: DM Sans, sans-serif; font-size: 0.85rem; cursor: pointer; transition: all 0.2s; text-align: center; }',
    '.rating-btn:hover { border-color: rgba(16,185,129,0.4); color: #10b981; }',
    '.rating-btn.selected { border-color: #10b981; background: rgba(16,185,129,0.1); color: #10b981; font-weight: 600; }',
    '.feedback-submit { width: 100%; background: #10b981; color: #0a1628; border: none; border-radius: 8px; padding: 11px; font-family: Syne, sans-serif; font-size: 0.9rem; font-weight: 600; cursor: pointer; margin-top: 0.75rem; }',
    '.feedback-submit:disabled { background: #1e3a2e; color: #3a6b55; cursor: not-allowed; }',
    '.feedback-thanks { text-align: center; padding: 1rem; color: #10b981; font-size: 0.9rem; display: none; }',
    '@media (max-width: 600px) { .field-row { grid-template-columns: 1fr; } .hero { padding: 2rem 1rem 1.5rem; } .form-container { padding: 1rem; } .result-section { padding: 0 1rem 2rem; } .form-card { padding: 1.25rem; } .rating-buttons { flex-direction: column; } }',
    '</style>',
    '</head>',
    '<body>',
    '<div class="hero">',
    '<div class="logo">Fund<span>ri</span></div>',
    '<div class="tagline">AI-Powered NGO Tools</div>',
    '<div class="tool-nav">',
    '<a href="/" class="tool-pill active">Fundability Audit</a>',
    '<a href="/story" class="tool-pill">Impact Story Builder</a>',
    '</div>',
    '<div class="badge">Free Audit Tool</div>',
    '<h1>Is your CSO ready to <em>get</em> funding?</h1>',
    '<p>Get an instant AI-powered audit of your organization\'s fundability &mdash; including gaps, recommended funders, and quick wins.</p>',
    '</div>',
    '<div class="form-container" id="formSection">',
    '<div class="form-card">',
    '<h2><span class="step-num">1</span> About your organization</h2>',
    '<div class="field-group">',
    '<label>Organization name</label>',
    '<input type="text" id="orgName" placeholder="e.g. Maji Safi Community Trust" />',
    '</div>',
    '<div class="field-row">',
    '<div class="field-group">',
    '<label>Primary sector</label>',
    '<select id="sector">',
    '<option value="">Select sector</option>',
    '<option>WASH (Water, Sanitation and Hygiene)</option>',
    '<option>Health</option>',
    '<option>Education</option>',
    '<option>Gender and Women Rights</option>',
    '<option>Climate and Environment</option>',
    '<option>Livelihoods and Economic Development</option>',
    '<option>Humanitarian and Emergency Relief</option>',
    '<option>Governance and Human Rights</option>',
    '<option>Food Security and Agriculture</option>',
    '</select>',
    '</div>',
    '<div class="field-group">',
    '<label>Annual budget (USD)</label>',
    '<select id="budget">',
    '<option value="">Select range</option>',
    '<option>Under $50,000</option>',
    '<option>$50,000 - $150,000</option>',
    '<option>$150,000 - $500,000</option>',
    '<option>$500,000 - $1,000,000</option>',
    '<option>Over $1,000,000</option>',
    '</select>',
    '</div>',
    '</div>',
    '<div class="field-row">',
    '<div class="field-group">',
    '<label>Country of operation</label>',
    '<input type="text" id="country" placeholder="e.g. Kenya, Uganda, Tanzania" />',
    '</div>',
    '<div class="field-group">',
    '<label>Years operating</label>',
    '<select id="years">',
    '<option value="">Select</option>',
    '<option>Less than 1 year</option>',
    '<option>1 - 3 years</option>',
    '<option>3 - 7 years</option>',
    '<option>7 - 15 years</option>',
    '<option>Over 15 years</option>',
    '</select>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="form-card">',
    '<h2><span class="step-num">2</span> Funding situation</h2>',
    '<div class="field-group">',
    '<label>Current or past funders (if any)</label>',
    '<input type="text" id="funders" placeholder="e.g. USAID, WaterAid, local government or none yet" />',
    '</div>',
    '<div class="field-group">',
    '<label>Biggest funding challenge right now</label>',
    '<textarea id="challenge" placeholder="e.g. We struggle to write competitive proposals..."></textarea>',
    '</div>',
    '<div class="field-group">',
    '<label>Key result or impact (your strongest evidence)</label>',
    '<textarea id="impact" placeholder="e.g. We provided clean water to 12,000 people across 8 villages in 2024..." style="min-height: 65px;"></textarea>',
    '</div>',
    '</div>',
    '<button class="submit-btn" onclick="runAudit()">Run my free fundability audit &#8594;</button>',
    '<div class="error-msg" id="errorMsg"></div>',
    '<p class="disclaimer" style="margin-top: 1rem;">Your org name is stored only to manage usage limits. Feedback you submit is stored to help us improve Fundri. Your data is never shared with third parties.</p>',
    '<p class="footer-contact">Get in touch &mdash; <a href="mailto:hello@getfundri.com">hello@getfundri.com</a></p>',
    '</div>',
    '<div class="result-section" id="resultSection">',
    '<div id="loadingState" class="loading-state result-card">',
    '<div class="spinner"></div>',
    '<p class="loading-title">Analyzing your organization...</p>',
    '<p>Running fundability assessment across 6 dimensions</p>',
    '</div>',
    '<div id="auditResults" style="display:none;">',
    '<div class="result-header">',
    '<div class="score-ring" id="scoreRing"><span class="score-number" id="scoreNum">--</span></div>',
    '<div class="score-label" id="scoreLabelText">Fundability Score</div>',
    '<div class="score-sub" id="scoreSubText"></div>',
    '</div>',
    '<div class="result-card"><h3>Overall assessment</h3><div class="result-content" id="overallText"></div></div>',
    '<div class="result-card"><h3>Top funding gaps identified</h3><div class="result-content" id="gapsText"></div></div>',
    '<div class="result-card"><h3>Recommended funders to target</h3><div class="result-content" id="fundersText"></div></div>',
    '<div class="result-card"><h3>Quick wins - do these this week</h3><div class="result-content" id="quickWinsText"></div></div>',
    '<div class="feedback-card">',
    '<h3>Was this audit useful?</h3>',
    '<div class="rating-buttons">',
    '<button class="rating-btn" onclick="selectRating(this, \'Yes\')">&#10003; Yes, very useful</button>',
    '<button class="rating-btn" onclick="selectRating(this, \'Somewhat\')">&#8776; Somewhat useful</button>',
    '<button class="rating-btn" onclick="selectRating(this, \'No\')">&#10007; Not really</button>',
    '</div>',
    '<div class="field-group">',
    '<label>Your feedback (optional)</label>',
    '<textarea id="feedbackComment" placeholder="What would make this more useful for your organization?" style="min-height: 70px;"></textarea>',
    '</div>',
    '<div class="field-group">',
    '<label>Your email (optional)</label>',
    '<input type="email" id="feedbackEmail" placeholder="hello@yourorg.org" />',
    '</div>',
    '<button class="feedback-submit" onclick="submitFeedback()" id="feedbackSubmitBtn">Send feedback</button>',
    '<div class="feedback-thanks" id="feedbackThanks">Thank you! Your feedback helps us improve Fundri.</div>',
    '</div>',
    '<button class="reset-btn" onclick="resetForm()">&#8592; Run another audit</button>',
    '<p class="footer-contact" style="margin-top: 1.5rem;">Get in touch &mdash; <a href="mailto:hello@getfundri.com">hello@getfundri.com</a></p>',
    '</div>',
    '</div>',
    '<script>',
    'var selectedRating = "";',
    'var currentOrg = "";',
    'function selectRating(btn, rating) {',
    '  selectedRating = rating;',
    '  document.querySelectorAll(".rating-btn").forEach(function(b) { b.classList.remove("selected"); });',
    '  btn.classList.add("selected");',
    '}',
    'async function submitFeedback() {',
    '  var btn = document.getElementById("feedbackSubmitBtn");',
    '  var comment = document.getElementById("feedbackComment").value.trim();',
    '  var email = document.getElementById("feedbackEmail").value.trim();',
    '  btn.disabled = true; btn.textContent = "Sending...";',
    '  try {',
    '    await fetch("/api/feedback", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    '      body: JSON.stringify({ rating: selectedRating, comment: comment, email: email, org: currentOrg })',
    '    });',
    '  } catch(e) {}',
    '  document.getElementById("feedbackThanks").style.display = "block";',
    '  btn.style.display = "none";',
    '}',
    'async function runAudit() {',
    '  var orgName = document.getElementById("orgName").value.trim();',
    '  var sector = document.getElementById("sector").value;',
    '  var budget = document.getElementById("budget").value;',
    '  var country = document.getElementById("country").value.trim();',
    '  var years = document.getElementById("years").value;',
    '  var funders = document.getElementById("funders").value.trim();',
    '  var challenge = document.getElementById("challenge").value.trim();',
    '  var impact = document.getElementById("impact").value.trim();',
    '  var errorMsg = document.getElementById("errorMsg");',
    '  errorMsg.style.display = "none";',
    '  if (!orgName || !sector || !budget || !country || !years || !challenge) {',
    '    errorMsg.textContent = "Please fill in all required fields before running your audit.";',
    '    errorMsg.style.display = "block"; return;',
    '  }',
    '  currentOrg = orgName;',
    '  var btn = document.querySelector(".submit-btn");',
    '  btn.disabled = true; btn.textContent = "Analyzing...";',
    '  document.getElementById("formSection").style.display = "none";',
    '  var resultSection = document.getElementById("resultSection");',
    '  resultSection.style.display = "block";',
    '  document.getElementById("loadingState").style.display = "block";',
    '  document.getElementById("auditResults").style.display = "none";',
    '  var prompt = "You are Fundri, an expert NGO fundability analyst for East African CSOs. Analyze this organization and return ONLY raw JSON with no markdown or backticks.\\n\\n";',
    '  prompt += "ORG: " + orgName + "\\n";',
    '  prompt += "Sector: " + sector + "\\n";',
    '  prompt += "Budget: " + budget + "\\n";',
    '  prompt += "Country: " + country + "\\n";',
    '  prompt += "Years: " + years + "\\n";',
    '  prompt += "Funders: " + (funders || "None") + "\\n";',
    '  prompt += "Challenge: " + challenge + "\\n";',
    '  prompt += "Impact: " + (impact || "Not provided") + "\\n\\n";',
    '  prompt += "Return this exact JSON: {score: number 1-100, scoreLabel: one of Early Stage/Developing/Competitive/Strong/Highly Fundable, scoreSummary: one sentence, overall: 3-4 sentences, gaps: 3 gaps each starting with bullet on new line, funders: 3 funders each starting with bullet on new line, quickWins: 3 actions each starting with bullet on new line}";',
    '  try {',
    '    var response = await fetch("/api/audit", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    '      body: JSON.stringify({ prompt: prompt, orgName: orgName })',
    '    });',
    '    var data = await response.json();',
    '    if (data.error === "already_submitted") {',
    '      document.getElementById("formSection").style.display = "block";',
    '      resultSection.style.display = "none";',
    '      errorMsg.textContent = "An audit for this organization has already been submitted. Email hello@getfundri.com to rerun.";',
    '      errorMsg.style.display = "block";',
    '      btn.disabled = false; btn.textContent = "Run my free fundability audit";',
    '      return;',
    '    }',
    '    var text = data.content[0].text.trim();',
    '    var result;',
    '    try { result = JSON.parse(text); }',
    '    catch(e) { var m = text.match(/\\{[\\s\\S]*\\}/); result = JSON.parse(m[0]); }',
    '    var score = Math.min(100, Math.max(1, parseInt(result.score)));',
    '    var pct = (score / 100 * 100).toFixed(0);',
    '    document.getElementById("scoreRing").style.setProperty("--score-pct", pct + "%");',
    '    document.getElementById("scoreNum").textContent = score;',
    '    document.getElementById("scoreLabelText").textContent = result.scoreLabel || "Fundability Score";',
    '    document.getElementById("scoreSubText").textContent = result.scoreSummary || "";',
    '    document.getElementById("overallText").textContent = result.overall || "";',
    '    document.getElementById("gapsText").textContent = result.gaps || "";',
    '    document.getElementById("fundersText").textContent = result.funders || "";',
    '    document.getElementById("quickWinsText").textContent = result.quickWins || "";',
    '    document.getElementById("loadingState").style.display = "none";',
    '    document.getElementById("auditResults").style.display = "block";',
    '  } catch(err) {',
    '    document.getElementById("formSection").style.display = "block";',
    '    resultSection.style.display = "none";',
    '    errorMsg.textContent = "Something went wrong. Please try again.";',
    '    errorMsg.style.display = "block";',
    '    btn.disabled = false; btn.textContent = "Run my free fundability audit";',
    '  }',
    '}',
    'function resetForm() {',
    '  document.getElementById("resultSection").style.display = "none";',
    '  document.getElementById("formSection").style.display = "block";',
    '  var btn = document.querySelector(".submit-btn");',
    '  btn.disabled = false; btn.textContent = "Run my free fundability audit";',
    '  selectedRating = "";',
    '  document.getElementById("feedbackComment").value = "";',
    '  document.getElementById("feedbackEmail").value = "";',
    '  document.getElementById("feedbackThanks").style.display = "none";',
    '  var fsBtn = document.getElementById("feedbackSubmitBtn");',
    '  fsBtn.style.display = "block"; fsBtn.disabled = false; fsBtn.textContent = "Send feedback";',
    '  document.querySelectorAll(".rating-btn").forEach(function(b) { b.classList.remove("selected"); });',
    '}',
    '<\/script>',
    '</body>',
    '</html>'
  ].join('\n');
  return html;
}
